[theme]
primaryColor="#FFFFFF"  #"#87CEEB" # Sky blue
backgroundColor="#F8FAFC" # Blanc très doux
secondaryBackgroundColor="#E2F3FB" # Bleu très clair
textColor="#0F172A" # Bleu foncé (lisible)
font="sans serif"
